global using System;
global using System.IO;
global using System.Reflection;
global using System.Diagnostics;
global using System.Runtime.Versioning;
global using System.Collections.Generic;
global using System.Security.Permissions;
global using System.Runtime.CompilerServices;
global using System.Text.RegularExpressions;
global using System.Linq;
global using MoreSlugcats;
global using RWCustom;
global using Expedition;
global using Noise;
global using BepInEx;
global using UnityEngine;
global using Random = UnityEngine.Random;
global using static PhysicalObject;
global using Pearlcat;
global using SlugpupStuff;
global using DevConsole;
global using DevConsole.Commands;
global using DressMySlugcat;
global using Menu.Remix.MixedUI;
global using Mono.Cecil.Cil;
global using MonoMod.RuntimeDetour;
global using MonoMod.Cil;