global using System;
global using System.IO;
global using System.Reflection;
global using System.Diagnostics;
global using System.Collections.Generic;
global using System.Runtime.CompilerServices;
global using System.Text.RegularExpressions;
global using System.Linq;
global using MoreSlugcats;
global using RWCustom;
global using Expedition;
global using Noise;
global using BepInEx;
global using UnityEngine;
global using Random = UnityEngine.Random;
global using SlugBase;
global using SlugBase.Features;
global using SlugBase.DataTypes;
global using static SlugBase.Features.FeatureTypes;
global using static PhysicalObject;
global using ImprovedInput;
global using DressMySlugcat;
global using Menu.Remix.MixedUI;
global using Mono.Cecil.Cil;
global using MonoMod.RuntimeDetour;
global using MonoMod.Cil;